# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse_api', '0005_remove_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='first_child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binder_root', to='muse_api.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='first_child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='muse_api.Document'),
        ),
    ]
