# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse_api', '0006_auto_20170712_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='next_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_node', to='muse_api.Document'),
        ),
    ]
